FROM ubuntu:xenial
MAINTAINER pyama86 <www.kazu.com@gmail.com>

RUN apt-get -qqy update && \
    apt-get install -qqy glibc-source gcc make \
                        bzip2 unzip debhelper dh-make devscripts cdbs clang libpam0g-dev git
